### PR TITLE
exercise-22

### PR DESCRIPTION
**Pull request by davicms**

### CODE REVIEW

**Comment by smbmatheus-lr** [comment]
Upgrading Clarity to 2024.q2

**Comment by dnebing** [comment]
Hey, so this PR is reporting conflicts?

**Comment by dnebing** [comment]
This PR still has merge conflicts...

Are we going to fix them or should I just close it?

**Comment by davicms** [comment]
Hey Dave! Matheus is having some days off and he will return next week... It's his call to do, yet I can try to solve the conflicts

**Comment by egnajek** [comment]
Closing this PR as @ricky-pan has already made the implementation change that is proposed here and after discussing with Davi.

**Pull request closed without merging**
